### ISSUE TITLE
Clone the repository

### ISSUE THREAD

**Issue by wemmyo** [wemmyo/Todo-tutorial#2]
Certainly! Here are detailed instructions on how to clone a GitHub repository:

---

## How to Clone a Repository from GitHub

**Objective:** By the end of this guide, you'll be able to clone the Todo-tutorial repository to your computer.

### Prerequisites

1. Make sure you have Git installed on your computer. If you don't have it yet, you can download and install it from [git-scm.com](https://git-scm.com/).

2. A GitHub account. If you don't have one, you can sign up at [github.com](https://github.com/).

### Instructions

1. **Open the GitHub repository**: Visit the repository URL 'https://github.com/wemmyo/Todo-tutorial.git' in your web browser.

2. **Locate the "Code" button**: On the right side of the page, you will see a green button labeled "Code". Click on it.

3. **Copy the repository URL**:
    - In the dropdown that appears, ensure that the "HTTPS" tab is selected.
    - Click the clipboard icon to the right of the repository URL. This copies the URL to your clipboard.

4. **Open your computer's terminal or command prompt**: 
    - On **Windows**, you can use the "Command Prompt" or "PowerShell".
    - On **macOS**, you can use the "Terminal" application.
    - On **Linux**, you can use any terminal application like "Terminal", "Konsole", etc.

5. **Navigate to the location where you want to clone the repository**: Use the `cd` command to navigate to a directory (folder) of your choice where you wish to save the cloned repository. 

   For example, if you want to navigate to a directory called "projects", you would type:
   ```
   cd path/to/projects
   ```

6. **Clone the repository**: Now, type the following command and then press Enter:

   ```
   git clone https://github.com/wemmyo/Todo-tutorial.git
   ```

   This will start the cloning process, and once it's complete, you'll have a copy of the "Todo-tutorial" repository on your computer.

7. **Navigate into the cloned directory**: 

   ```
   cd Todo-tutorial
   ```

   Now, you're inside the directory of the cloned repository and ready to start coding!

---

**Comment by Calli94** [comment]
![git](https://github.com/wemmyo/Todo-tutorial/assets/146876783/0c722765-dfa5-4627-9618-f2f8b144140c)

Done
