### ISSUE TITLE
Checkout to Your Individual Branch

### ISSUE THREAD

**Issue by wemmyo** [wemmyo/Todo-tutorial#3]
# Issue: Checkout to Your Individual Branch

## Description
Before we dive into creating our files and making changes, it's essential to ensure that each of you is working in your dedicated branch. This will help keep your work isolated, making it easier to manage, review, and integrate later.

## Objective
Ensure each student is working on their individual branch.

### Using VSCode's Integrated Terminal
All the Git commands provided in the instructions below should be executed in the integrated terminal of VSCode. Here's how to access it:

1. **Open VSCode**.
2. From the menu bar, go to `View` > `Terminal`. This will open the terminal at the bottom of your VSCode window.
3. Make sure the opened terminal is set to the correct path of your project directory.

Now, follow the steps below in the terminal:

1. **Ensure You Have the Latest Version of the Repository**:
   - Pull the latest changes from the main repository (if you haven't already cloned it):
     ```
     git clone <repository-url>
     ```

2. **Checkout to Your Branch**:
   - Based on your name or identifier, switch to your respective branch. 
     - For Student A: (Calli)
       ```
       git checkout student-a-branch
       ```
     - For Student B: (Richie)
       ```
       git checkout student-b-branch
       ```

   **Note**: If you encounter an error stating that the branch doesn't exist, reach out for guidance.

3. **Verify Your Branch**:
   - Ensure that you've successfully switched to your branch:
     ```
     git branch
     ```
   You should see an asterisk (*) next to your branch name, indicating that you're on the correct branch.

4. **Push Any Changes (If Made)**:
   - If you make any changes or start any work, remember to push to your branch:
     ```
     git push origin <your-branch-name>
     ```

5. **Comment on this Issue**:
   - Once you've switched to your branch, please comment on this issue confirming the same. This ensures everyone is on the right track.

## Acceptance Criteria
- Each student should be working on their designated branch.
- The branch should be verified using the `git branch` command.
- Confirmation comment on this issue from each student.

---

**End of Issue**

**Comment by Rikyi3** [comment]
git branch changed to <studentAA> 
no Bs for me

**Comment by Rikyi3** [comment]
changed to student AA

**Comment by Calli94** [comment]
trying to create the branch but keep getting this error message:

PS D:\GitRepository\Repository\Calli> git checkout student-a-branch
fatal: not a git repository (or any of the parent directories): .git

**Comment by Calli94** [comment]
Help

**Comment by Calli94** [comment]
![got branch ](https://github.com/wemmyo/Todo-tutorial/assets/146876783/4245e65a-4720-4ab4-9039-e00ca366b1e7)

**Comment by Calli94** [comment]
Done

**Comment by Calli94** [comment]
But I can't see the asterisk on my Branch Name

**Comment by Calli94** [comment]
@Rikyi3 try this: 
 git checkout -b Student-BB-Branch

**Comment by Calli94** [comment]
![got branch ](https://github.com/wemmyo/Todo-tutorial/assets/146876783/785affc1-04a6-4dd4-811a-3fc6f60cc6ff)

**Comment by Calli94** [comment]
DONE
